# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    my_user_provider.class: CoreBundle\Security\User\FOSUBUserProvider

services:
    my_user_provider:
        class: "%my_user_provider.class%"
        arguments: ["@fos_user.user_manager",{facebook: facebook_id}]